#!/bin/bash

#Checking to see if Drupal already exists. If it does then won't copy from /usr/src/ otherwise we will.


if [ $(ls /var/www/html/ | grep --quiet -v 'index.html\|phpinfo.php'; echo $?) != "1"  ]; then
  echo "Drupal appears to already be installed, no action taken."
  exit 0
fi

if [ -e "/var/www/html/sites/default/settings.php" ]; then
  	echo "Drupal appears to already be installed, no action taken."
    exit 0
elif [ -e "/var/www/html/sites/default/default.settings.php" ]; then
  	echo "Drupal appears to already be installed, no action taken."
    exit 0
else
    echo "Installing Drupal."
    tar -xz --strip-components=1 -f /usr/src/drupal.tar.gz -C /var/www/html/
fi
